// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSBCHVrTOFsB32FjMFADSF5KAk3ruVbbI',
    appId: '1:468927522979:web:b74f577645fc7b8bb3f716',
    messagingSenderId: '468927522979',
    projectId: 'coworkingtracker',
    authDomain: 'coworkingtracker.firebaseapp.com',
    storageBucket: 'coworkingtracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_HdAx4XyXTfUBEYaSuFvbkbA-vIprLUw',
    appId: '1:468927522979:android:58268f339268ac7fb3f716',
    messagingSenderId: '468927522979',
    projectId: 'coworkingtracker',
    storageBucket: 'coworkingtracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk8mKbZIVyYahyqX7XXQPw2-rUcqsjoGU',
    appId: '1:468927522979:ios:8c08d51cf83a00e9b3f716',
    messagingSenderId: '468927522979',
    projectId: 'coworkingtracker',
    storageBucket: 'coworkingtracker.appspot.com',
    iosClientId: '468927522979-52umdru2ue82htfdmhalbd8f7qgvh41o.apps.googleusercontent.com',
    iosBundleId: 'com.example.cowork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk8mKbZIVyYahyqX7XXQPw2-rUcqsjoGU',
    appId: '1:468927522979:ios:8c08d51cf83a00e9b3f716',
    messagingSenderId: '468927522979',
    projectId: 'coworkingtracker',
    storageBucket: 'coworkingtracker.appspot.com',
    iosClientId: '468927522979-52umdru2ue82htfdmhalbd8f7qgvh41o.apps.googleusercontent.com',
    iosBundleId: 'com.example.cowork',
  );
}
